# Generated by Django 3.0.8 on 2020-08-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo_photos/'),
        ),
    ]
