# Generated by Django 3.0.8 on 2020-08-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200801_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='photo_weight',
            new_name='photo_width',
        ),
    ]
