# Generated by Django 3.0.8 on 2020-08-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200801_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='photo_height',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='photo_width',
        ),
    ]
