# Generated by Django 3.0.8 on 2020-08-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='picture',
        ),
    ]
